`use strict`;

export const modulePrefix = {
  security: `security`,
  dynamicSql: `dynamicSql`,
  postInfo: `postInfo`,
  postCommentInfo: `postCommentInfo`,
  edocComponentTemplate: `edocComponentTemplate`,
  edocDocument: `edocDocument`,
  edocCustom: `edocCustom`,
};

export const messages = {
  SITE_DESCRIPTION: `Brunner-Next now provides a document management platform that enables you to create and manage electronic documents in real time using an electronic document designer.`,
  EMPTY_STRING: "",
  DATABASE_FAILED: `Database failed.`,
  DELETE_ITEM: `Delete this item?`,
  DELETE_SELECTED_PAGE: `Do you want to delete current selected page?`,
  EMAIL_NOT_VALID: `The [email] is not valid.`,
  FAILED_TO_DELETE_DATA: `Failed to delete data.`,
  FAILED_TO_INSERT_DATA: `Failed to insert data.`,
  FAILED_TO_SAVE_DATA: `Failed to save data.`,
  FAILED_TO_UPDATE_DATA: `Failed to update data.`,
  FAILED_REQUESTED: `Failed to request service.`,
  INVALIED_NUMBER_AMOUNT: `Invalid number or amount.`,
  LOGIN_REQUIRED: "Login Required.",
  MINIUM_PAGE_COUNT: `Minimum page count is 1.`,
  NOT_SET_API_ENDPOINT: `API endpoint is not set.`,
  NOT_SUPPORTED_API_METHOD: `Not supported API method. Only GET and POST are supported.`,
  NO_DATA_FOUND: `No data found.`,
  NO_PERMISSION: `You do not have permission`,
  REQUIRED_FIELD: `The field value is required.`,
  SERVER_NOT_CONNECTTED: `cannot connect to server`,
  SERVER_NOT_SUPPORTED_MODULE: `Not supported module`,
  SERVER_NOW_INITIALIZING: `Server is now initializing...`,
  SERVER_NO_COMMAND_NAME: `No commandName provided in request.`,
  SERVER_SQL_NOT_LOADED: `Service SQL not loaded.`,
  SIGNOUT: `Do you want to signout now?`,
  SUCCESS_ADDED: `Successfully added.`,
  SUCCESS_CHANGED: `Successfully changed.`,
  SUCCESS_DELETED: `Successfully deleted.`,
  SUCCESS_FINISHED: `Successfully finished.`,
  SUCCESS_REQUESTED: `Successfully requested.`,
  SUCCESS_SAVED: `Successfully saved.`,
  SUCCESS_SIGNUP: `successfully signed up.`,
  PHONE_NUMBER_NOT_VALID: `The [phoneNumber] is not valid.`,
  PHONE_NUMBER_OR_EMAIL_NOT_VALID: `Invalid user phone number or E-Mail.`,
  UNKNOWN_ERROR: `Unknown error occured.`,
  USER_ID_NOT_EXIST: `The [userId] does not exist.`,
  USER_ID_LENGTH_CHECK: `The [userId] length should be from 5 to 10.`,
  USER_NAME_LENGTH_CHECK: `The [password] length should be more than 5.`,
  USER_PASSWORD_LENGTH_CHECK: `The [password] length should be more than 5.`,
};

export const commands = {
  DYNAMIC_SEQ_SELECT_ALL: `dynamicSql.selectAll`,
  DYNAMIC_SEQ_UPDATE_ONE: `dynamicSql.updateOne`,
  DYNAMIC_SEQ_DELETE_ONE: `dynamicSql.deleteOne`,
  DYNAMIC_SEQ_LOAD_ALL: `dynamicSql.loadAll`,

  SECURITY_DELETE_ACCOUNT: `security.deleteAccount`,
  SECURITY_RESET_PASSWORD: `security.resetPassword`,
  SECURITY_SEND_EMAIL_AUTHCODE: `security.sendEMailAuthCode`,
  SECURITY_SIGNOUT: `security.signout`,
  SECURITY_SIGNUP: `security.signup`,
  SECURITY_SIGNIN: `security.signin`,

  POST_INFO_INSERT_ONE: `postInfo.insertOne`,
  POST_INFO_UPDATE_ONE: `postInfo.updateOne`,
  POST_INFO_DELETE_ONE: `postInfo.deleteOne`,
  POST_INFO_SELECT_ALL: `postInfo.selectAll`,

  POST_COMMENT_INFO_INSERT_ONE: `postCommentInfo.insertOne`,
  POST_COMMENT_INFO_UPDATE_ONE: `postCommentInfo.updateOne`,
  POST_COMMENT_INFO_DELETE_ONE: `postCommentInfo.deleteOne`,

  EDOC_COMPONENT_TEMPLATES_SELECT_ALL: `edocComponentTemplate.selectAll`,
  EDOC_DOCUMENT_UPSERT_ONE: `edocDocument.upsertOne`,
  EDOC_DOCUMENT_SELECT_ONE: `edocDocument.selectOne`,
  EDOC_DOCUMENT_DELETE_ONE: `edocDocument.deleteOne`,
  EDOC_USER_DOCUMENT_SELECT_ALL: `edocDocument.slectUserAll`,
  EDOC_ADMIN_DOCUMENT_SELECT_ALL: `edocDocument.slectAdminAll`,
  EDOC_AI_GET_MODEL_LIST: `edocDocument.getAIModelList`,
  EDOC_AI_GENERATE_DOCUMENT: `edocDocument.generateAIDocument`,
};

export const edocComponentType = {
  _TEXT: `text`,
  _TABLE: `table`,
  _IMAGE: `image`,
  _INPUT: `input`,
  _CHECKLIST: `checklist`,
  _BUTTON: `button`,
  _VIDEO: `video`,
  _LINKTEXT: 'linkText'
};
